var w=t=>{throw TypeError(t)};var k=(t,e,a)=>e.has(t)||w("Cannot "+a);var r=(t,e,a)=>(k(t,e,"read from private field"),a?a.call(t):e.get(t)),c=(t,e,a)=>e.has(t)?w("Cannot add the same private member more than once"):e instanceof WeakSet?e.add(t):e.set(t,a),i=(t,e,a,n)=>(k(t,e,"write to private field"),n?n.call(t,a):e.set(t,a),a);import{a as T,S as $,i as v}from"./assets/vendor-Db2TdIkw.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))n(s);new MutationObserver(s=>{for(const l of s)if(l.type==="childList")for(const L of l.addedNodes)L.tagName==="LINK"&&L.rel==="modulepreload"&&n(L)}).observe(document,{childList:!0,subtree:!0});function a(s){const l={};return s.integrity&&(l.integrity=s.integrity),s.referrerPolicy&&(l.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?l.credentials="include":s.crossOrigin==="anonymous"?l.credentials="omit":l.credentials="same-origin",l}function n(s){if(s.ep)return;s.ep=!0;const l=a(s);fetch(s.href,l)}})();var u,h,d,p,y,m;class x{constructor(e){c(this,u);c(this,h);c(this,d);c(this,p);c(this,y);c(this,m);i(this,u,e.q),i(this,h,e.key),i(this,d,e.image_type),i(this,p,e.orientation),i(this,y,e.safesearch),i(this,m,e.url)}getData(){const e={key:r(this,h),q:r(this,u),image_type:r(this,d),orientation:r(this,p),safesearch:r(this,y)};return T.get(r(this,m),{params:e})}get q(){return r(this,u)}set q(e){i(this,u,e)}get key(){return r(this,h)}set key(e){i(this,h,e)}get imageType(){return r(this,d)}set imageType(e){i(this,d,e)}get orientation(){return r(this,p)}set orientation(e){i(this,p,e)}get safesearch(){return r(this,y)}set safesearch(e){i(this,y,e)}get url(){return r(this,m)}set url(e){i(this,m,e)}}u=new WeakMap,h=new WeakMap,d=new WeakMap,p=new WeakMap,y=new WeakMap,m=new WeakMap;var g;class M{constructor(e){c(this,g);this.array=e,i(this,g,null)}set renderDiv(e){i(this,g,e)}createMarkup(){r(this,g).innerHTML="";const e=this.array.map(n=>`<li class="gallery-item">
    <a class="image-link" href="${n.largeImageURL}"><img class="image" src="${n.webformatURL}" alt="${n.tags}" title=""/></a>
    <ul class="image-descr-list">
<li class="descr-item">Likes<span class="descr-span">${n.likes}</span></li>
<li class="descr-item">Views<span class="descr-span">${n.views}</span></li>
<li class="descr-item">Comments<span class="descr-span">${n.comments}</span></li>
<li class="descr-item">Downloads<span class="descr-span">${n.downloads}</span></li>
    </ul>
    </li>`).join("");r(this,g).insertAdjacentHTML("beforeend",e),new $(".gallery-item a").refresh()}}g=new WeakMap;const D=document.querySelector(".gallery"),S=document.querySelector(".form"),f=S.elements[0];f.classList.add("input");const P=S.elements[1];P.classList.add("button");const q=document.querySelector(".loader");q.style.display="none";const o=new x({});o.key="49512194-f753c2f34a7e7dbbd609db53f";o.q="";o.imageType="photo";o.orientation="horizontal";o.safesearch=!0;o.url="https://pixabay.com/api/";const b=new M([]);P.addEventListener("click",O);function O(t){if(t.preventDefault(),b.renderDiv=D,q.style.display="flex",o.q=f.value,f.value="",o.q===""){v.error({message:"Write your something you want to see",position:"topRight"}),q.style.display="none";return}o.getData().then(e=>{if(e.data.hits.length===0){q.style.display="none",v.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),D.innerHTML="",f.value="",o.q="";return}b.array=e.data.hits,b.createMarkup(b.array),q.style.display="none",f.value="",o.q=""}).catch(e=>{v.error({message:"Bad request",position:"topRight"}),q.style.display="none",f.value="",o.q=""})}
//# sourceMappingURL=index.js.map
