import{a as p,S as f,i as l}from"./assets/vendor-Db2TdIkw.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();function g(t){const s={key:"49512194-f753c2f34a7e7dbbd609db53f",q:t,imageType:"photo",orientation:"horizontal",safesearch:!0,url:"https://pixabay.com/api/"};return p.get(s.url,{params:s})}function y(t,s){const a=s.map(e=>`<li class="gallery-item">
    <a class="image-link" href="${e.largeImageURL}"><img class="image" src="${e.webformatURL}" alt="${e.tags}" title=""/></a>
    <ul class="image-descr-list">
<li class="descr-item">Likes<span class="descr-span">${e.likes}</span></li>
<li class="descr-item">Views<span class="descr-span">${e.views}</span></li>
<li class="descr-item">Comments<span class="descr-span">${e.comments}</span></li>
<li class="descr-item">Downloads<span class="descr-span">${e.downloads}</span></li>
    </ul>
    </li>`).join("");t.insertAdjacentHTML("beforeend",a),new f(".gallery-item a",{captionsData:"alt",captionDelay:250}).refresh()}function h(t){t.innerHTML=""}function L(){const t=document.querySelector(".loader");t.style.display="flex"}function c(){const t=document.querySelector(".loader");t.style.display="none"}const u=document.querySelector(".gallery"),d=document.querySelector(".form"),o=d.elements[0];o.classList.add("input");const m=d.elements[1];m.classList.add("button");m.addEventListener("click",b);function b(t){if(t.preventDefault(),h(u),L(),o.value===""){c(),l.error({message:"Write your something you want to see",position:"topRight"});return}g(o.value).then(s=>{if(s.data.hits.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(u,s.data.hits)}).catch(()=>{l.error({message:"Bad request",position:"topRight"})}).finally(()=>{c(),o.value=""})}
//# sourceMappingURL=index.js.map
